services:
  postgres:
    image: postgres:15
    container_name: qa_test_db
    environment:
      POSTGRES_USER: qa_user
      POSTGRES_PASSWORD: qa_pass
      POSTGRES_DB: qa_database
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  my_api:  # ADD THIS SECTION
    build: .  # Tells Docker to build the API from your current folder
    container_name: qa_api
    ports:
      - "8000:8000"  # This opens localhost:8000
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DATABASE_URL=postgresql://qa_user:qa_pass@postgres:5432/qa_database